<!-- Bootstrap core JavaScript-->
  <script src="{{ asset('admin') }}/assets/js/jquery.min.js"></script>
  <script src="{{ asset('admin') }}/assets/js/popper.min.js"></script>
  <script src="{{ asset('admin') }}/assets/js/bootstrap.min.js"></script>
  <!-- simplebar js -->
  <script src="{{ asset('admin') }}/assets/plugins/simplebar/js/simplebar.js"></script>
  <!-- sidebar-menu js -->
  <script src="{{ asset('admin') }}/assets/js/sidebar-menu.js"></script>
  <!-- loader scripts -->
  <script src="{{ asset('admin') }}/assets/js/jquery.loading-indicator.js"></script>
  <!-- Custom scripts -->
  <script src="{{ asset('admin') }}/assets/js/app-script.js"></script>
  <!-- Chart js -->
  <script src="{{ asset('admin') }}/assets/plugins/Chart.js/Chart.min.js"></script>
  <!-- Index js -->
  <script src="{{ asset('admin') }}/assets/js/index.js"></script>